# Generated by Django 5.2.6 on 2025-09-22 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age must be between 13-23 for this platform', null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_peer_matching',
            field=models.BooleanField(default=True, help_text='Allow matching with peers for support'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us a bit about yourself', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='crisis_contact_phone',
            field=models.CharField(blank=True, help_text='Emergency contact number (optional)', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_anonymous_preferred',
            field=models.BooleanField(default=True, help_text='Prefer anonymous interactions in community features'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_mood_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(default=dict, help_text='User notification preferences'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='specializations',
            field=models.JSONField(default=list, help_text='Areas of mental health specialization'),
        ),
        migrations.AddField(
            model_name='user',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Standard User'), ('guide', 'Guide/Mentor'), ('admin', 'Administrator')], default='user', max_length=10),
        ),
        migrations.AlterModelTable(
            name='user',
            table='accounts_user',
        ),
    ]
    