services:
  # Test-specific PostgreSQL configuration
  db:
    environment:
      POSTGRES_DB: test_edumindsolutions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    command: postgres -c log_statement=all -c log_destination=stderr

  # Test-specific Redis configuration
  redis:
    command: redis-server --appendonly no --save "" --maxmemory 128mb --maxmemory-policy allkeys-lru

  # Test backend service
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DEBUG=1
      - TESTING=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/test_edumindsolutions
      - REDIS_URL=redis://redis:6379/1
      - DJANGO_SETTINGS_MODULE=backend.settings
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend-test
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate --run-syncdb &&
             python manage.py runserver 0.0.0.0:8000"
    profiles:
      - testing

  # Test frontend service
  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=test
      - REACT_APP_API_URL=http://localhost:8001/api
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend-test
    command: npm start
    profiles:
      - testing

volumes:
  postgres_test_data:
  