# Generated by Django 5.2.6 on 2025-10-06 14:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_add_assessment_requests_and_assignments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clientassessmentassignment',
            name='unique_guide_client_assessment',
        ),
        migrations.AlterUniqueTogether(
            name='clientassessmentassignment',
            unique_together={('guide', 'client', 'assessment_type')},
        ),
    ]
    