# Generated by Django 5.2.6 on 2025-09-22 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('clinic', 'Mental Health Clinic'), ('hospital', 'Hospital'), ('psychologist', 'Psychologist'), ('psychiatrist', 'Psychiatrist'), ('counselor', 'Counselor'), ('support_group', 'Support Group'), ('crisis_line', 'Crisis Hotline'), ('online_service', 'Online Service')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('services_offered', models.JSONField(default=list, help_text='List of services offered')),
                ('specializations', models.JSONField(default=list, help_text='Areas of specialization')),
                ('age_groups_served', models.JSONField(default=list, help_text='Age groups served')),
                ('languages', models.JSONField(default=list, help_text='Languages spoken')),
                ('hours_of_operation', models.JSONField(default=dict, help_text='Operating hours by day')),
                ('is_24_7', models.BooleanField(default=False)),
                ('accepts_walk_ins', models.BooleanField(default=False)),
                ('cost_level', models.CharField(choices=[('free', 'Free'), ('low_cost', 'Low Cost'), ('insurance', 'Insurance Accepted'), ('private_pay', 'Private Pay')], max_length=20)),
                ('insurance_accepted', models.JSONField(default=list, help_text='Insurance providers accepted')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_mental_health_resource',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='content.contentcategory')),
            ],
            options={
                'verbose_name': 'Content Category',
                'verbose_name_plural': 'Content Categories',
                'db_table': 'content_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AudioContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('audio_type', models.CharField(choices=[('meditation', 'Guided Meditation'), ('breathing', 'Breathing Exercise'), ('podcast', 'Podcast Episode'), ('affirmation', 'Affirmations'), ('story', 'Calming Story')], max_length=20)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('audio_url', models.URLField(blank=True, help_text='External audio URL if not uploaded')),
                ('duration_seconds', models.PositiveIntegerField()),
                ('tags', models.JSONField(default=list)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='audio_thumbnails/')),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_audio', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_content', to='content.contentcategory')),
            ],
            options={
                'db_table': 'content_audio',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(help_text='Brief summary for previews', max_length=300)),
                ('content', models.TextField()),
                ('tags', models.JSONField(default=list, help_text='List of tags for filtering')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('estimated_read_time', models.PositiveIntegerField(help_text='Estimated reading time in minutes')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='content.contentcategory')),
            ],
            options={
                'db_table': 'content_article',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.URLField(help_text='YouTube, Vimeo, or other video platform URL')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('duration_seconds', models.PositiveIntegerField(help_text='Video duration in seconds')),
                ('tags', models.JSONField(default=list)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_videos', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.contentcategory')),
            ],
            options={
                'db_table': 'content_video',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('audio', 'Audio')], max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('action_type', models.CharField(choices=[('view', 'Viewed'), ('like', 'Liked'), ('share', 'Shared'), ('bookmark', 'Bookmarked'), ('complete', 'Completed')], max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Time spent on content', null=True)),
                ('completion_percentage', models.PositiveIntegerField(blank=True, help_text='Percentage completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_engagement',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'content_type', 'content_id', 'action_type')},
            },
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('audio', 'Audio')], max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_user_bookmark',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
    ]
    