# Generated by Django 5.2.6 on 2025-09-22 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisHotline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('hotline_type', models.CharField(choices=[('suicide_prevention', 'Suicide Prevention'), ('crisis_text', 'Crisis Text Line'), ('domestic_violence', 'Domestic Violence'), ('substance_abuse', 'Substance Abuse'), ('lgbtq', 'LGBTQ+ Support'), ('teen_specific', 'Teen-Specific'), ('general_mental_health', 'General Mental Health'), ('emergency', 'Emergency Services')], max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('text_number', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('chat_url', models.URLField(blank=True, help_text='Online chat URL')),
                ('is_24_7', models.BooleanField(default=True)),
                ('hours_description', models.CharField(blank=True, max_length=200)),
                ('languages', models.JSONField(default=list, help_text='Languages supported')),
                ('country', models.CharField(default='United States', max_length=100)),
                ('regions_served', models.JSONField(default=list, help_text='States/regions served')),
                ('is_international', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('priority_order', models.PositiveIntegerField(default=0, help_text='Display order priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crisis_hotline',
                'ordering': ['priority_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CrisisResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('immediate_coping', 'Immediate Coping Strategy'), ('breathing_exercise', 'Breathing Exercise'), ('grounding_technique', 'Grounding Technique'), ('safety_plan', 'Safety Planning'), ('distraction_activity', 'Distraction Activity'), ('emergency_contacts', 'Emergency Contacts')], max_length=30)),
                ('instructions', models.TextField(help_text='Step-by-step instructions')),
                ('estimated_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('crisis_situations', models.JSONField(default=list, help_text='Applicable crisis situations')),
                ('age_appropriate', models.JSONField(default=list, help_text='Appropriate age ranges')),
                ('is_active', models.BooleanField(default=True)),
                ('priority_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crisis_resource',
                'ordering': ['priority_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CrisisAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('self_reported', 'Self-Reported Crisis'), ('sentiment_detected', 'Sentiment Analysis Alert'), ('assessment_triggered', 'Assessment Score Alert'), ('keyword_detected', 'Keyword Detection'), ('behavior_pattern', 'Concerning Behavior Pattern')], max_length=30)),
                ('severity_level', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk'), ('imminent', 'Imminent Danger')], max_length=20)),
                ('trigger_content', models.TextField(blank=True, help_text='Content that triggered the alert')),
                ('context_data', models.JSONField(default=dict, help_text='Additional context information')),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='active', max_length=20)),
                ('response_notes', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=True)),
                ('follow_up_completed', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crisis_responses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crisis_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSafetyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_signs', models.JSONField(default=list, help_text='Personal warning signs')),
                ('triggers', models.JSONField(default=list, help_text='Known triggers')),
                ('coping_strategies', models.JSONField(default=list, help_text='Personal coping strategies')),
                ('distractions', models.JSONField(default=list, help_text='Healthy distractions')),
                ('support_contacts', models.JSONField(default=list, help_text='Personal support contacts')),
                ('professional_contacts', models.JSONField(default=list, help_text='Mental health professionals')),
                ('environment_safety', models.JSONField(default=list, help_text='Environmental safety measures')),
                ('emergency_contacts', models.JSONField(default=list, help_text='Emergency contacts')),
                ('emergency_plan', models.TextField(blank=True, help_text='Emergency action plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crisis_user_safety_plan',
            },
        ),
    ]
    